apiVersion: v1
kind: ConfigMap
metadata:
  name: krush0-config
  labels:
    app.kubernetes.io/name: krush0
data:
  INSTANCE_DOMAIN: 'api.topia.io'
  INSTANCE_PROTOCOL: 'https'
  INTERACTIVE_KEY: 'X8OxYRIjSfRaWoM0ywSl'
  NODE_ENV: 'production'
  PORT: '3000'
