import { 
  STREAK_MULTIPLIER_LOW,
  STREAK_MULTIPLIER_MID,
  STREAK_MULTIPLIER_HIGH,
  STREAK_MULTIPLIER_HIGHER,
  STREAK_MULTIPLIER_HIGHEST,
  STREAK_MULTIPLIER_MID_THRESHOLD,
  STREAK_MULTIPLIER_HIGH_THRESHOLD,
  STREAK_MULTIPLIER_HIGHER_THRESHOLD,
  STREAK_MULTIPLIER_HIGHEST_THRESHOLD
} from '../data/gameConstants'

// function to calculate streak
export const getStreakMultiplier = (streak: number): number => {
  if (streak < STREAK_MULTIPLIER_MID_THRESHOLD) return STREAK_MULTIPLIER_LOW
  else if (streak < STREAK_MULTIPLIER_HIGH_THRESHOLD) return STREAK_MULTIPLIER_MID
  else if (streak < STREAK_MULTIPLIER_HIGHER_THRESHOLD) return STREAK_MULTIPLIER_HIGH
  else if (streak < STREAK_MULTIPLIER_HIGHEST_THRESHOLD) return STREAK_MULTIPLIER_HIGHER
  else return STREAK_MULTIPLIER_HIGHEST
}